//UI相关
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_SEARCH_PANEL = 'TOGGLE_SEARCH_PANEL';

//Player
export const PLAYER_SET_AUDIO = 'PLAYER_SET_AUDIO';
export const PLAYER_GET_TRACKS = 'PLAYER_GET_TRACKS';
export const PLAYER_SET_PLAY = 'PLAYER_SET_PLAY';
export const PLAYER_SET_CURRENT_TIME = 'PLAYER_SET_CURRENT_TIME';
export const PLAYER_SET_TRACK = 'PLAYER_SET_TRACK';
export const PLAYER_SET_PLAYMODE = 'PLAYER_SET_PLAYMODE';
export const PLAYER_OPEN_PLAYLIST = 'PLAYER_OPEN_PLAYLIST';
export const PLAYER_OPEN_LYRIC = 'PLAYER_OPEN_LYRIC';

//API相关
export const GET_REQUEST = 'GET_REQUEST';
export const GET_REQUEST_FAILURE = 'GET_REQUEST_FAILURE';
export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
export const FETCH_PLAYLIST_DETAIL = 'FETCH_PLAYLIST_DETAIL';
export const FETCH_PLAYLIST_CATEGORY = 'FETCH_PLAYLIST_CATEGORY';
export const FETCH_PLAYLIST_HOT = 'FETCH_PLAYLIST_HOT';
export const FETCH_PLAYLIST_COMMENT = 'FETCH_PLAYLIST_COMMENT';
export const FETCH_PLAYLIST_SUBSCRIBER = 'FETCH_PLAYLIST_SUBSCRIBER';
export const FETCH_SONG_DETAIL = 'FETCH_SONG_DETAIL';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_HOT = 'FETCH_SEARCH_HOT';
export const FETCH_SEARCH_SUGGEST = 'FETCH_SEARCH_SUGGEST';
export const FETCH_TOPLIST = 'FETCH_TOPLIST';
export const FETCH_TOPLIST_DETAIL = 'FETCH_TOPLIST_DETAIL';
export const FETCH_ARTIST = 'FETCH_ARTIST';
export const FETCH_TOP_ARTIST = 'FETCH_TOP_ARTIST';
export const FETCH_TOP_ARTIST_MORE = 'FETCH_TOP_ARTIST_MORE';
export const FETCH_ARTIST_ALBUM = 'FETCH_ARTIST_ALBUM';
export const FETCH_ARTIST_MV = 'FETCH_ARTIST_MV';
export const FETCH_ARTIST_DESC = 'FETCH_ARTIST_DESC';
export const FETCH_ARTIST_SIMI = 'FETCH_ARTIST_SIMI';
export const FETCH_ALBUM = 'FETCH_ALBUM';
export const FETCH_ALBUM_COMMENT = 'FETCH_ALBUM_COMMENT';
export const FETCH_SONG_URL = 'FETCH_SONG_URL';
export const FETCH_LYRIC = 'FETCH_LYRIC';
